#!/usr/bin/env python3
"""Convert a Markdown document to a readable PDF.

The script is intentionally dependency-light and reusable for future skill
deliverables. It focuses on Chinese-friendly resume/project reports generated by
this repository: headings, blockquotes, bullets, ordered lists, tables, links,
inline code, bold text and code blocks.

Dependency:
    python -m pip install reportlab

Usage:
    python jdhunter/references/markdown_to_pdf.py \
        jd-match-resume-pack.md

    python jdhunter/references/markdown_to_pdf.py \
        input.md --output output.pdf --title "JD 匹配项目推荐报告"
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path
from typing import Iterable

try:
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import cm
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.cidfonts import UnicodeCIDFont
    from reportlab.pdfbase.ttfonts import TTFont
    from reportlab.platypus import (
        HRFlowable,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )
except ImportError as exc:  # pragma: no cover - exercised by users without deps
    raise SystemExit(
        "Missing dependency: reportlab. Install it with: "
        "python -m pip install reportlab"
    ) from exc


LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
INLINE_CODE_RE = re.compile(r"`([^`]+)`")
BOLD_RE = re.compile(r"\*\*([^*]+)\*\*")
ORDERED_RE = re.compile(r"^\s*\d+[.)]\s+(.+)$")
UNORDERED_RE = re.compile(r"^\s*[-*+]\s+(.+)$")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.+)$")
TABLE_SEPARATOR_RE = re.compile(r"^\s*\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?\s*$")
PROJECT_HEADING_RE = re.compile(r"^推荐项目\s*\d+[:：]")


def register_cjk_font() -> str:
    """Register and return a font name that can render Chinese text."""
    font_candidates = [
        Path(r"C:\Windows\Fonts\msyh.ttc"),
        Path(r"C:\Windows\Fonts\simhei.ttf"),
        Path(r"C:\Windows\Fonts\simsun.ttc"),
        Path(r"C:\Windows\Fonts\NotoSansCJK-Regular.ttc"),
        Path("/System/Library/Fonts/PingFang.ttc"),
        Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"),
        Path("/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc"),
        Path("/usr/share/fonts/truetype/wqy/wqy-microhei.ttc"),
    ]

    for font_path in font_candidates:
        if not font_path.exists():
            continue
        for kwargs in ({"subfontIndex": 0}, {}):
            try:
                pdfmetrics.registerFont(TTFont("ReadableCJK", str(font_path), **kwargs))
                return "ReadableCJK"
            except Exception:
                continue

    pdfmetrics.registerFont(UnicodeCIDFont("STSong-Light"))
    return "STSong-Light"


def make_styles(font_name: str) -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    styles: dict[str, ParagraphStyle] = {}

    styles["title"] = ParagraphStyle(
        "ReadableTitle",
        parent=base["Title"],
        fontName=font_name,
        fontSize=21,
        leading=28,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#111827"),
        spaceAfter=18,
        wordWrap="CJK",
        splitLongWords=0,
    )
    styles["cover_title"] = ParagraphStyle(
        "ReadableCoverTitle",
        parent=base["Title"],
        fontName=font_name,
        fontSize=26,
        leading=34,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=10,
        wordWrap="CJK",
        splitLongWords=0,
    )
    styles["cover_subtitle"] = ParagraphStyle(
        "ReadableCoverSubtitle",
        parent=base["BodyText"],
        fontName=font_name,
        fontSize=11.5,
        leading=18,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#475569"),
        spaceAfter=18,
        wordWrap="CJK",
        splitLongWords=0,
    )
    styles["h1"] = ParagraphStyle(
        "ReadableH1",
        parent=base["Heading1"],
        fontName=font_name,
        fontSize=18,
        leading=24,
        textColor=colors.HexColor("#111827"),
        spaceBefore=18,
        spaceAfter=10,
        wordWrap="CJK",
        splitLongWords=0,
    )
    styles["h2"] = ParagraphStyle(
        "ReadableH2",
        parent=base["Heading2"],
        fontName=font_name,
        fontSize=15,
        leading=21,
        textColor=colors.HexColor("#1f2937"),
        spaceBefore=14,
        spaceAfter=8,
        wordWrap="CJK",
        splitLongWords=0,
    )
    styles["h2_bar"] = ParagraphStyle(
        "ReadableH2Bar",
        parent=styles["h2"],
        textColor=colors.HexColor("#0f172a"),
        spaceBefore=0,
        spaceAfter=0,
    )
    styles["h3"] = ParagraphStyle(
        "ReadableH3",
        parent=base["Heading3"],
        fontName=font_name,
        fontSize=13,
        leading=19,
        textColor=colors.HexColor("#374151"),
        spaceBefore=10,
        spaceAfter=6,
        wordWrap="CJK",
        splitLongWords=0,
    )
    styles["h4"] = ParagraphStyle(
        "ReadableH4",
        parent=styles["h3"],
        fontSize=11.5,
        leading=17,
        textColor=colors.HexColor("#0f766e"),
        spaceBefore=8,
        spaceAfter=4,
        wordWrap="CJK",
        splitLongWords=0,
    )
    styles["body"] = ParagraphStyle(
        "ReadableBody",
        parent=base["BodyText"],
        fontName=font_name,
        fontSize=10.5,
        leading=17,
        alignment=TA_LEFT,
        textColor=colors.HexColor("#1f2937"),
        spaceAfter=6,
        wordWrap="CJK",
        splitLongWords=0,
    )
    styles["bullet"] = ParagraphStyle(
        "ReadableBullet",
        parent=styles["body"],
        leftIndent=14,
        firstLineIndent=-9,
        spaceAfter=4,
        wordWrap="CJK",
        splitLongWords=0,
    )
    styles["callout"] = ParagraphStyle(
        "ReadableCallout",
        parent=styles["body"],
        fontSize=10,
        leading=16,
        leftIndent=8,
        rightIndent=8,
        borderColor=colors.HexColor("#bae6fd"),
        borderWidth=0.8,
        borderPadding=7,
        backColor=colors.HexColor("#f0f9ff"),
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=8,
        wordWrap="CJK",
        splitLongWords=0,
    )
    styles["quote"] = ParagraphStyle(
        "ReadableQuote",
        parent=styles["body"],
        leftIndent=12,
        rightIndent=8,
        borderColor=colors.HexColor("#cbd5e1"),
        borderWidth=0.8,
        borderPadding=6,
        backColor=colors.HexColor("#f8fafc"),
        textColor=colors.HexColor("#475569"),
        spaceAfter=8,
        wordWrap="CJK",
        splitLongWords=0,
    )
    styles["code"] = ParagraphStyle(
        "ReadableCode",
        parent=styles["body"],
        fontName="Courier",
        fontSize=8.5,
        leading=12,
        leftIndent=8,
        rightIndent=8,
        borderColor=colors.HexColor("#e5e7eb"),
        borderWidth=0.6,
        borderPadding=6,
        backColor=colors.HexColor("#f9fafb"),
        textColor=colors.HexColor("#111827"),
        wordWrap="CJK",
        splitLongWords=0,
    )
    styles["table"] = ParagraphStyle(
        "ReadableTable",
        parent=styles["body"],
        fontSize=8.5,
        leading=12,
        spaceAfter=0,
        wordWrap="CJK",
        splitLongWords=0,
    )
    styles["toc"] = ParagraphStyle(
        "ReadableTOC",
        parent=styles["body"],
        fontSize=10,
        leading=16,
        leftIndent=8,
        spaceAfter=2,
        wordWrap="CJK",
        splitLongWords=0,
    )
    return styles


def heading_card(
    text: str,
    styles: dict[str, ParagraphStyle],
    available_width: float,
    *,
    project: bool = False,
) -> Table:
    background = colors.HexColor("#eaf2ff") if not project else colors.HexColor("#edf7ff")
    border = colors.HexColor("#bfdbfe") if not project else colors.HexColor("#bae6fd")
    table = Table(
        [[Paragraph(clean_inline_markdown(text), styles["h2_bar"])]],
        colWidths=[available_width],
        hAlign="LEFT",
    )
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), background),
                ("BOX", (0, 0), (-1, -1), 0.8, border),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    return table


def extract_cover(markdown_text: str) -> tuple[str, list[tuple[str, str]], str]:
    lines = markdown_text.splitlines()
    title = "Markdown Report"
    meta: list[tuple[str, str]] = []
    start_index = 0

    if lines and lines[0].startswith("# "):
        title = lines[0].removeprefix("# ").strip()
        start_index = 1

    while start_index < len(lines) and not lines[start_index].strip():
        start_index += 1

    while start_index < len(lines) and lines[start_index].strip().startswith(">"):
        item = lines[start_index].strip().lstrip("> ").strip()
        if "：" in item:
            key, value = item.split("：", 1)
        elif ":" in item:
            key, value = item.split(":", 1)
        else:
            key, value = "说明", item
        meta.append((key.strip(), value.strip()))
        start_index += 1

    remaining = "\n".join(lines[start_index:]).lstrip()
    return title, meta, remaining


def build_cover(
    title: str,
    meta: list[tuple[str, str]],
    styles: dict[str, ParagraphStyle],
    available_width: float,
) -> list:
    story: list = [Spacer(1, 2.3 * cm)]
    story.append(Paragraph(clean_inline_markdown(title), styles["cover_title"]))
    story.append(
        Paragraph(
            "业务型 Agent 项目选择报告 · 源码验证版 · 简历改造路线",
            styles["cover_subtitle"],
        )
    )
    story.append(HRFlowable(width="45%", thickness=1.0, color=colors.HexColor("#93c5fd")))
    story.append(Spacer(1, 0.55 * cm))

    if meta:
        meta_rows = [
            [Paragraph(f"<b>{clean_inline_markdown(key)}</b>", styles["table"]), Paragraph(clean_inline_markdown(value), styles["table"])]
            for key, value in meta
        ]
        table = Table(meta_rows, colWidths=[3.0 * cm, available_width - 3.0 * cm])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e0f2fe")),
                    ("BACKGROUND", (1, 0), (1, -1), colors.HexColor("#f8fafc")),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 7),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        story.append(table)
        story.append(Spacer(1, 0.45 * cm))

    story.append(PageBreak())
    return story


def clean_inline_markdown(text: str) -> str:
    escaped = html.escape(text.strip())
    escaped = LINK_RE.sub(r'<a href="\2" color="#2563eb">\1</a>', escaped)
    escaped = BOLD_RE.sub(r"<b>\1</b>", escaped)
    escaped = INLINE_CODE_RE.sub(r"\1", escaped)
    return escaped.replace("  ", "&nbsp;&nbsp;")


def is_table_block(lines: list[str], index: int) -> bool:
    return (
        index + 1 < len(lines)
        and "|" in lines[index]
        and bool(TABLE_SEPARATOR_RE.match(lines[index + 1]))
    )


def split_table_row(line: str) -> list[str]:
    stripped = line.strip()
    if stripped.startswith("|"):
        stripped = stripped[1:]
    if stripped.endswith("|"):
        stripped = stripped[:-1]
    return [cell.strip() for cell in stripped.split("|")]


def build_table(
    table_lines: list[str], styles: dict[str, ParagraphStyle], available_width: float
) -> Table:
    rows = [split_table_row(line) for line in table_lines if line.strip()]
    if len(rows) >= 2 and TABLE_SEPARATOR_RE.match(table_lines[1]):
        rows = [rows[0], *rows[2:]]

    column_count = max(len(row) for row in rows)
    normalized_rows = [row + [""] * (column_count - len(row)) for row in rows]
    data = [
        [Paragraph(clean_inline_markdown(cell), styles["table"]) for cell in row]
        for row in normalized_rows
    ]
    col_widths = [available_width / column_count] * column_count
    table = Table(data, colWidths=col_widths, repeatRows=1, hAlign="LEFT")
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dbeafe")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#111827")),
                ("FONTNAME", (0, 0), (-1, -1), styles["body"].fontName),
                ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#cbd5e1")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ]
        )
    )
    return table


def gather_paragraph(lines: list[str], index: int) -> tuple[str, int]:
    parts: list[str] = []
    while index < len(lines):
        line = lines[index]
        stripped = line.strip()
        if not stripped:
            break
        if HEADING_RE.match(stripped) or UNORDERED_RE.match(stripped) or ORDERED_RE.match(stripped):
            break
        if stripped.startswith(">") or stripped.startswith("```") or is_table_block(lines, index):
            break
        parts.append(stripped)
        index += 1
    return " ".join(parts), index


def parse_markdown(
    markdown_text: str, styles: dict[str, ParagraphStyle], available_width: float
) -> list:
    lines = markdown_text.splitlines()
    story: list = []
    index = 0
    in_code_block = False
    code_lines: list[str] = []
    first_heading_rendered = False

    while index < len(lines):
        raw_line = lines[index]
        line = raw_line.rstrip()
        stripped = line.strip()

        if stripped.startswith("```"):
            if in_code_block:
                story.append(Paragraph("<br/>".join(html.escape(x) for x in code_lines), styles["code"]))
                story.append(Spacer(1, 6))
                code_lines = []
                in_code_block = False
            else:
                in_code_block = True
            index += 1
            continue

        if in_code_block:
            code_lines.append(line)
            index += 1
            continue

        if not stripped:
            story.append(Spacer(1, 4))
            index += 1
            continue

        heading = HEADING_RE.match(stripped)
        if heading:
            level = len(heading.group(1))
            text = clean_inline_markdown(heading.group(2))
            raw_heading_text = heading.group(2).strip()
            if level == 2 and PROJECT_HEADING_RE.match(raw_heading_text) and story:
                story.append(PageBreak())
            if level == 1 and not first_heading_rendered:
                story.append(Paragraph(text, styles["title"]))
                first_heading_rendered = True
            elif level == 2:
                story.append(Spacer(1, 8))
                story.append(heading_card(raw_heading_text, styles, available_width, project=bool(PROJECT_HEADING_RE.match(raw_heading_text))))
                story.append(Spacer(1, 8))
            else:
                style_name = "h1" if level == 1 else "h3" if level == 3 else "h4"
                story.append(Paragraph(text, styles[style_name]))
            index += 1
            continue

        if stripped == "---":
            story.append(HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#cbd5e1")))
            story.append(Spacer(1, 8))
            index += 1
            continue

        if is_table_block(lines, index):
            table_lines = [lines[index], lines[index + 1]]
            index += 2
            while index < len(lines) and "|" in lines[index] and lines[index].strip():
                table_lines.append(lines[index])
                index += 1
            story.append(build_table(table_lines, styles, available_width))
            story.append(Spacer(1, 8))
            continue

        if stripped.startswith(">"):
            quote_lines: list[str] = []
            while index < len(lines) and lines[index].strip().startswith(">"):
                quote_lines.append(lines[index].strip().lstrip("> "))
                index += 1
            story.append(Paragraph("<br/>".join(clean_inline_markdown(x) for x in quote_lines), styles["quote"]))
            continue

        unordered = UNORDERED_RE.match(line)
        ordered = ORDERED_RE.match(line)
        if unordered or ordered:
            marker = "•" if unordered else "#"
            text = unordered.group(1) if unordered else ordered.group(1)
            if marker == "#":
                marker = f"{len([x for x in story if False]) + 1}."
            cleaned = clean_inline_markdown(text)
            if "：" in text and len(text.split("：", 1)[0]) <= 12:
                key, value = text.split("：", 1)
                cleaned = f"<b>{clean_inline_markdown(key)}</b>：{clean_inline_markdown(value)}"
            story.append(Paragraph(f"• {cleaned}", styles["bullet"]))
            index += 1
            continue

        paragraph, next_index = gather_paragraph(lines, index)
        if paragraph:
            story.append(Paragraph(clean_inline_markdown(paragraph), styles["body"]))
            index = next_index
        else:
            index += 1

    return story


def add_page_number(canvas, doc) -> None:  # noqa: ANN001 - reportlab callback
    if doc.page == 1:
        return
    canvas.saveState()
    canvas.setFont(doc.font_name, 8)
    canvas.setFillColor(colors.HexColor("#64748b"))
    canvas.line(1.55 * cm, 1.18 * cm, A4[0] - 1.55 * cm, 1.18 * cm)
    canvas.drawString(1.55 * cm, A4[1] - 1.0 * cm, doc.title[:42])
    canvas.drawRightString(A4[0] - 1.55 * cm, 1.0 * cm, f"第 {doc.page - 1} 页")
    canvas.restoreState()


def convert_markdown_to_pdf(input_path: Path, output_path: Path, title: str | None = None) -> None:
    if not input_path.exists():
        raise FileNotFoundError(f"Markdown file not found: {input_path}")

    font_name = register_cjk_font()
    styles = make_styles(font_name)
    text = input_path.read_text(encoding="utf-8")
    report_title, cover_meta, body_text = extract_cover(text)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        rightMargin=1.55 * cm,
        leftMargin=1.55 * cm,
        topMargin=1.45 * cm,
        bottomMargin=1.55 * cm,
        title=title or report_title or input_path.stem,
        author="jdhunter",
    )
    doc.font_name = font_name
    story = build_cover(
        title or report_title,
        cover_meta,
        styles,
        doc.width,
    )
    story.extend(parse_markdown(body_text, styles, doc.width))
    doc.build(story, onFirstPage=add_page_number, onLaterPages=add_page_number)


def default_output_path(input_path: Path) -> Path:
    return input_path.with_suffix(".pdf")


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert Markdown to a readable PDF.")
    parser.add_argument("input", type=Path, help="Path to the Markdown file.")
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        help="Output PDF path. Default: same path as input with .pdf suffix.",
    )
    parser.add_argument("--title", help="PDF document title metadata.")
    return parser.parse_args(argv)


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(argv)
    output_path = args.output or default_output_path(args.input)
    convert_markdown_to_pdf(args.input, output_path, args.title)
    print(f"PDF written: {output_path.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
